name: Update Folder Structure and Deploy

on:
  push:
    branches:
      - main

jobs:
  update-structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Generate folder structure
      run: |
        import os
        import json

        def get_structure(path):
            result = {}
            for item in os.listdir(path):
                if item.startswith('.') or item == 'structure.json':
                    continue
                full_path = os.path.join(path, item)
                if os.path.isdir(full_path):
                    result[item] = get_structure(full_path)
                elif os.path.dirname(full_path) != '.':  # Only include files if they're not in the root directory
                    result[item] = None
            return result

        structure = get_structure('.')
        # Only keep top-level folders
        structure = {k: v for k, v in structure.items() if isinstance(v, dict)}
        with open('structure.json', 'w') as f:
            json.dump(structure, f, indent=2)
      shell: python
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add structure.json
        git commit -m "Update folder structure" || echo "No changes to commit"
        git push origin main
    - name: Verify file existence
      run: |
        if [ -f "structure.json" ]; then
          echo "structure.json exists"
        else
          echo "structure.json does not exist"
          exit 1
        fi

  deploy:
    needs: update-structure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
